"""Added user deposit.

Revision ID: 32b690e12792
Revises: edea8eca3ae8
Create Date: 2018-08-27 12:05:11.203173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b690e12792'
down_revision = 'edea8eca3ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deposit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deposit')
    # ### end Alembic commands ###
