"""Changed global settings values to nullable.

Revision ID: 47af861cde66
Revises: 6f5368288797
Create Date: 2018-08-31 02:05:05.938604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47af861cde66'
down_revision = '6f5368288797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_setting', 'value',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_setting', 'value',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=64),
               nullable=False)
    # ### end Alembic commands ###
