"""Added name in global settings.

Revision ID: 6f5368288797
Revises: d666735dc3c3
Create Date: 2018-08-31 01:22:45.105234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5368288797'
down_revision = 'd666735dc3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_setting', sa.Column('name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_setting', 'name')
    # ### end Alembic commands ###
