"""Added is_quantifiable to items

Revision ID: 829631f2c5d5
Revises: f10fdb24d666
Create Date: 2018-08-02 22:12:14.792203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829631f2c5d5'
down_revision = 'f10fdb24d666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_quantifiable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_quantifiable')
    # ### end Alembic commands ###
