"""Added observer, customer, bartender and admin accounts.

Revision ID: 936990b0d7b4
Revises: effccaede53f
Create Date: 2018-12-27 18:40:54.813797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936990b0d7b4'
down_revision = 'effccaede53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_customer', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_observer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_observer')
    op.drop_column('user', 'is_customer')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
