"""added item quantity

Revision ID: cb36d79b785c
Revises: 547f3d741dba
Create Date: 2018-07-29 14:56:36.167103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb36d79b785c'
down_revision = '547f3d741dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'quantity')
    # ### end Alembic commands ###
