"""Simple name change.

Revision ID: effccaede53f
Revises: f6d7ffed36d0
Create Date: 2018-09-05 10:15:04.542685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'effccaede53f'
down_revision = 'f6d7ffed36d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.drop_column('item', 'favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('favorite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('item', 'is_favorite')
    # ### end Alembic commands ###
