"""completed transaction table

Revision ID: f10fdb24d666
Revises: cb36d79b785c
Create Date: 2018-07-30 00:47:44.886663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10fdb24d666'
down_revision = 'cb36d79b785c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('balance_change', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('type', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_transaction_type'), 'transaction', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_type'), table_name='transaction')
    op.drop_column('transaction', 'type')
    op.drop_column('transaction', 'balance_change')
    # ### end Alembic commands ###
